TrajectoryPlannerROS:
    holonomic_robot: false # important!
    # setup limits
    max_vel_x : 0.1
    min_vel_x : 0.07 # faster plz

    escape_vel: -0.1 # backing up

    min_vel_y : 0.0
    max_vel_y : 0.0

    max_vel_theta : 0.09 # lower?
    min_in_place_vel_theta : 0.06

    acc_lim_x : 3.5
    acc_lim_theta : 3.2
    acc_lim_y : 0.0

    #tolerances
    yaw_goal_tolernace: 0.26 #15 degrees
    xy_goal_tolerance: 0.30  #15 cm

    vx_samples: 8
    vy_samples: 1