obstacle_range: 1.0
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
holonomic_robot: false
robot_radius: .3
inflation_radius: 1.0

observation_sources: laser_scan_sensor #point_cloud_sensor is for sonar later, set laser clearing to false for this.

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}