obstacle_range: 3.0
min_obstacle_height: -0.1
max_obstacle_height: 0.1
raytrace_range: 5.5
holonomic_robot: false
footprint: [[0.4, 0.2], [0.4, -0.2], [-0.3,-0.2], [-0.3,0.2]]

map_type: costmap
publish_frequency: 1.0

obstacle_layer:
    observation_sources: scan
    track_unknown_space: true
    scan: {data_type: LaserScan, sensor_frame: /laser, topic: /scan, clearing: true, marking: true, expected_update_rate: 1.0}

inflation_layer:
    enabled : True 
    cost_scaling_factor: 5
    inflation_radius: 0.2

static_layer:
    enabled: true
